/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, { Component } from "react";
import { Platform, StyleSheet, Text, View, Image } from "react-native";
import resolveAssetSource from "react-native/Libraries/Image/resolveAssetSource";
import { Warper, WarpView } from "react-native-warper";
import config from "./new.pb";

export default class App extends Component {
  state = {
    status: "starting",
    message: "--"
  };
  componentDidMount() {
    Warper.sampleMethod("Testing", 123, message => {
      this.setState({
        status: "native callback received",
        message
      });
    });
  }
  render() {
    console.log("WarpView", typeof WarpView, "Warper", Warper);
    return (
      <View style={styles.container}>
        <WarpView
          uri={Image.resolveAssetSource(config).uri}
          style={{ width: "100%", height: "100%" }}
        >
          <Text style={styles.welcome}>☆Warper example☆</Text>
          <Text style={styles.instructions}>STATUS: {this.state.status}</Text>
          <Text style={styles.welcome}>☆NATIVE CALLBACK MESSAGE☆</Text>
          <Text style={styles.instructions}>{this.state.message}</Text>
          <Text>{JSON.stringify(resolveAssetSource(config))}</Text>
        </WarpView>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#F5FCFF"
  },
  welcome: {
    fontSize: 20,
    textAlign: "center",
    margin: 10
  },
  instructions: {
    textAlign: "center",
    color: "#333333",
    marginBottom: 5
  }
});
